// Code generated by goctl. DO NOT EDIT.
package types

type GetUserInfoReq struct {
	Id int64 `json:"id"`
}

type GetUserInfoResp struct {
	Id        int64  `json:"id"`
	Username  string `json:"username"`
	Avatar    string `json:"avatar"`
	Level     int64  `json:"level"`
	Exp       int64  `json:"exp"`
	Gold      int64  `json:"gold"`
	Diamond   int64  `json:"diamond"`
	LandLevel int64  `json:"landLevel"`
	Extra     string `json:"extra"`
}

type LoginReq struct {
	Username string `json:"username" binding:"required"`
	Password string `json:"password" binding:"required"`
}

type LoginResp struct {
	Id       int64  `json:"id"`
	Name     string `json:"name"`
	Token    string `json:"token"`
	ExpireAt string `json:"expireAt"`
}

type PingReq struct {
	Id int64 `json:"id"`
}

type PingResp struct {
	Result string `json:"result"`
}

type RegisterReq struct {
	Username string `json:"username" binding:"required"`
	Password string `json:"password" binding:"required"`
}

type RegisterResp struct {
	Id       int64  `json:"id"`
	Name     string `json:"name"`
	Token    string `json:"token"`
	ExpireAt string `json:"expireAt"`
}

type UpdateUserInfoReq struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

type UpdateUserInfoResp struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}
