// Code generated by goctl. DO NOT EDIT.
// Source: rpcdemo.proto

package server

import (
	"context"

	"gozerodemo.com/rpcdemo/internal/logic"
	"gozerodemo.com/rpcdemo/internal/svc"
	"gozerodemo.com/rpcdemo/rpcdemo"
)

type RpcdemoServer struct {
	svcCtx *svc.ServiceContext
	rpcdemo.UnimplementedRpcdemoServer
}

func NewRpcdemoServer(svcCtx *svc.ServiceContext) *RpcdemoServer {
	return &RpcdemoServer{
		svcCtx: svcCtx,
	}
}

func (s *RpcdemoServer) Ping(ctx context.Context, in *rpcdemo.Request) (*rpcdemo.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *RpcdemoServer) SayHello(ctx context.Context, in *rpcdemo.SayHelloReq) (*rpcdemo.SayHelloResp, error) {
	l := logic.NewSayHelloLogic(ctx, s.svcCtx)
	return l.SayHello(in)
}
